// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyModularMonolith.Modules.Gyms.Infrastructure;

#nullable disable

namespace MyModularMonolith.Modules.Gyms.Infrastructure.Migrations
{
    [DbContext(typeof(GymsDbContext))]
    [Migration("20250917063713_AddProducts")]
    partial class AddProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Gyms")
                .HasAnnotation("ProductVersion", "10.0.0-preview.7.25380.108")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyModularMonolith.Modules.Gyms.Domain.Gym", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.HasIndex("Name", "IsActive");

                    b.ToTable("Gyms", "Gyms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Gym Central"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Gym Norte"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Gym Sur"
                        });
                });

            modelBuilder.Entity("MyModularMonolith.Modules.Gyms.Domain.GymProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Equipment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InstructorEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("InstructorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InstructorPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<int?>("MinCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProductId");

                    b.HasIndex("GymId", "IsActive");

                    b.HasIndex("GymId", "ProductId")
                        .IsUnique();

                    b.ToTable("GymProducts", "Gyms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-aaaa-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GymId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsActive = true,
                            MaxCapacity = 50,
                            Price = 35.00m,
                            ProductId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Schedule = "{}"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-bbbb-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GymId = new Guid("33333333-3333-3333-3333-333333333333"),
                            InstructorName = "Carlos Rodríguez",
                            IsActive = true,
                            MaxCapacity = 20,
                            MinCapacity = 5,
                            Price = 15.00m,
                            ProductId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Schedule = "{\"monday\":[\"19:00-20:00\"],\"wednesday\":[\"19:00-20:00\"],\"friday\":[\"19:00-20:00\"]}"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-aaaa-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 10.0m,
                            GymId = new Guid("44444444-4444-4444-4444-444444444444"),
                            IsActive = true,
                            MaxCapacity = 40,
                            Price = 30.00m,
                            ProductId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Schedule = "{}"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-eeee-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GymId = new Guid("44444444-4444-4444-4444-444444444444"),
                            InstructorName = "María González",
                            IsActive = true,
                            MaxCapacity = 25,
                            MinCapacity = 8,
                            Price = 12.00m,
                            ProductId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Schedule = "{\"tuesday\":[\"18:30-19:30\"],\"thursday\":[\"18:30-19:30\"],\"saturday\":[\"10:00-11:00\"]}"
                        });
                });

            modelBuilder.Entity("MyModularMonolith.Modules.Gyms.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("HasCapacityLimits")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("RequiresInstructor")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresSchedule")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("Products", "Gyms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BasePrice = 35.00m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Acceso completo a la sala de musculación con equipos de última generación",
                            HasCapacityLimits = true,
                            IsActive = true,
                            Name = "Acceso Sala de Musculación",
                            RequiresInstructor = false,
                            RequiresSchedule = false
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            BasePrice = 15.00m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clase de spinning de alta intensidad con música motivadora",
                            HasCapacityLimits = true,
                            IsActive = true,
                            Name = "Clase de Spinning",
                            RequiresInstructor = true,
                            RequiresSchedule = true
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            BasePrice = 45.00m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sesión de entrenamiento personalizado con instructor especializado",
                            HasCapacityLimits = false,
                            IsActive = true,
                            Name = "Entrenamiento Personal",
                            RequiresInstructor = true,
                            RequiresSchedule = true
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            BasePrice = 50.00m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Consulta personalizada con nutricionista certificado",
                            HasCapacityLimits = false,
                            IsActive = true,
                            Name = "Consulta Nutricional",
                            RequiresInstructor = true,
                            RequiresSchedule = true
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            BasePrice = 12.00m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clase de zumba divertida y energética para todos los niveles",
                            HasCapacityLimits = true,
                            IsActive = true,
                            Name = "Clase de Zumba",
                            RequiresInstructor = true,
                            RequiresSchedule = true
                        });
                });

            modelBuilder.Entity("MyModularMonolith.Modules.Gyms.Domain.GymProduct", b =>
                {
                    b.HasOne("MyModularMonolith.Modules.Gyms.Domain.Gym", "Gym")
                        .WithMany("GymProducts")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyModularMonolith.Modules.Gyms.Domain.Product", "Product")
                        .WithMany("GymProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MyModularMonolith.Modules.Gyms.Domain.Gym", b =>
                {
                    b.Navigation("GymProducts");
                });

            modelBuilder.Entity("MyModularMonolith.Modules.Gyms.Domain.Product", b =>
                {
                    b.Navigation("GymProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
