<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ErrorOr" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\src\MyModularMonolith.ServiceDefaults\MyModularMonolith.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
